### ISSUE TITLE
Can we rename the repo "cheesein"?

### ISSUE THREAD

**Issue by DDCreationStudios** [cheesein/cheesein#18]
Can we rename either the repo "cheesein" or the organization "cheesein".
It's super confusing right now.
Since our last talk I would recommend renaming the **repo** to 

- "Basic functionality" or 
- "Base" or 
- "Backend" 

These are just suggestions. We really need something different than the organization name itself 😆 💯

**Comment by lumio** [comment]
Well, this is a good question 😄  Counter question: why is it confusing to have the main repo called cheesein? Many other open source projects have the same naming convention (e.g. angular/angular or webpack/webpack)

The only reason - in my opinion - I would rename this repo is if we split backend and frontend in 2 separate repositories, leading to a 3rd repository to combine both with submodules.

I would then suggest the following repository names:
* cheesein/backend
* cheesein/frontend
* cheesein/cheesein-build

There are contrary opinions on the web about splitting the repository.
You may look at the following 2 posts:
* Pro: https://quickleft.com/blog/six-reasons-we-split-front-end-and-back-end-code-into-two-git-repositories-working-with-github-repositories/
* Contra: http://softwareengineering.stackexchange.com/questions/194822/when-to-separate-a-project-in-multiple-subprojects#answer-194861

**Comment by DDCreationStudios** [comment]
OK, ok when it's standing practice to have this kind of naming I think it's better to have it that way. A seperation of front- and backend isn't really necessay from my point of view. Coming from a different background, I was just wondering and it seemed not practical to use exactly the same name.

**Comment by lumio** [comment]
No worries 😄

**Comment by lumio** [comment]
Reading on https://quickleft.com/blog/six-reasons-we-split-front-end-and-back-end-code-into-two-git-repositories-working-with-github-repositories/

Point 6 is a real big deal in the near future, where we might have to have separate releases for back- and frontend. The question is, if we want to have separate releases or if we say, we have backend and frontend some sort of bundle which makes sense as well.
I think this is more a decision of taste in the end

**Comment by DDCreationStudios** [comment]
Let's talk about that also in the next meeting 😉

**Comment by lumio** [comment]
We discussed this and came to the conclusion that we have our codebase separated in different folders.
