### ISSUE TITLE
Removing "sprint planning"?

### ISSUE THREAD

**Issue by lumio** [cheesein/cheesein#19]
It looks like we won't use githubs Project view that much. I think we could just work with just the Issues view. What do you think?

Or should we leave it for now in hope to use it in the near future?

**Comment by DDCreationStudios** [comment]
Actually I am using it and changed a few things just yesterday :D.
Let's keep it and play with it to get a general feeling. It also provides a nice visualization of our issues. I am confident that it will provide a nice orientation when the project is bigger.
