### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by DDCreationStudios** [cheesein/cheesein#32]
Choose a suitable license 
http://choosealicense.com/licenses/

**Comment by lumio** [comment]
See [pull request here](https://github.com/cheesein/cheesein/pull/33)

**Comment by lumio** [comment]
I think GNU GPLv3 is good enough. I think if someone wants to add external modules (separate code base), that someone might still be able to charge for their module.

But the code base of CheeseIn should stay open source.

**Comment by DDCreationStudios** [comment]
Proposing GNU AGPLv3 since it is the  GNU GPLv3 just with added remedy of the network distribution problem! Suits your idea of open source better!
The practical aspect of user charging for this project is not really possible, since the seller has to indicate, that it is also free available 😆

**Comment by lumio** [comment]
Sounds good. I don't think we need to discuss that. But I let it open for now.
I merged your license into master.
